#' @title Apply test
#' @param setup the setup class
test_summary <- function(setup, ...) {
  UseMethod("test_summary", object = setup)
  
}

test_summary.default <- function(setup, ...) {
  
  warning(paste("apply_test does not know how to handle object of class ",
                class(setup),
                "and can only be used on classes column or merge"))
  
}

#' @title Creates a summary of the test
#' @inheritParams test
#' @return dataframe
#' @export
test_summary.column <- function(setup, ...) {
  
  t <- test(setup, df)
  
  d <- data.frame(test_category = t$test_category,
             df_name = t$df_name,
             col_name = t$col_name,
             test_name = t$test_name,
             test_desc = t$test_desc,
             test_result = t$test_result,
             test_message = t$test_message)
  
  return(d)
  
}

#' @title Create row for test merge
#' @param test the test class generated by one of the test functions
#' @export
test_summary.merge <- function(setup, ...){
  
  t <- test(setup, primary_df, related_df)
  
  d <- data.frame(test_category = t$test_category,
             primary_df = t$primary_df,
             related_df = t$related_df,
             test_name = t$test_name,
             test_desc = t$test_desc,
             test_result = t$test_result,
             test_message = t$test_message)
  
  return(d)
  
}

# test_specific <- function() {}
# 
# test_specific.default <- function(setup) {
#   
#   data.frame(
#     df_name = setup$problem_df$df_name,
#     col_name = setup$problem_df$col_name,
#     date = setup$problem_df$lubridate::today())
# }
