passed <- "PASSED"
failed <- "FAILED"

#' @title Create test row
#' @param test the test class generated by one of the test functions
#' @examples
#' test <- test_na(df, cls)
#' test_row(test)
test_row <- function(test) {
  
  data.frame(df_name = test$df_name,
             col_name = test$col_name,
             test_name = test$test_name,
             test_desc = test$test_desc,
             test_result = test$test_result,
             test_message = test$test_message)
  
}

#' @title Apply test
#' @export
apply_test <- function(setup, df){
  UseMethod("apply_test")
  
}

apply_test.default <- function(setup, df, ...){
  
  warning(paste("apply_test does not know how to handle object of class ", 
                class(setup),
                "and can only be used on classes test_na, test_unique, test_values, and test_range"))
  
}

#' @title Tests for NAs
#' @export
apply_test.test_na <- function(setup, df) {
  
  cls <- class_test_na(setup)
  test <- test_na(df, cls)
  test_result <- test_row(test)
  
  return(test_result)
}

#' @title Tests for uniqueness
#' @export
apply_test.test_unique <- function(setup, df) {
  
  cls <- class_test_unique(setup)
  test <- test_unique(df, cls)
  test_result <- test_row(test)
  
  return(test_result)
}

#' @title Tests for Values
#' @export
apply_test.test_values <- function(setup, df) {
  
  cls <- class_test_values(setup)
  test <- test_values(df, cls)
  test_result <- test_row(test)
  
  return(test_result)
}

#' @title Tests Range of Values
#' @export
apply_test.test_range <- function(setup, df) {
  
  cls <- class_test_range(setup)
  test <- test_range(df, cls)
  test_result <- test_row(test)
  
  return(test_result)
}
