passed <- "PASSED"
failed <- "FAILED"

#' @title Create test row
#' @param test the test class generated by one of the test functions
#' @examples
#' test <- test_na(df, cls)
#' test_row(test)
test_row <- function(test) {
  
  data.frame(df_name = test$df_name,
             col_name = test$col_name,
             test_name = test$test_name,
             test_desc = test$test_desc,
             test_result = test$test_result,
             test_message = test$test_message)
  
}

#' @title Setup Test Range
#' @export
setup_test_range <- function(df_name, col_name, int, lower_inclu, 
                             upper_inclu, lower, upper, na) {
  
  structure(list(test_name = "test_range", 
        df_name = df_name,
        col_name = col_name,
        int = int,
        lower_inclu = lower_inclu,
        upper_inclu = upper_inclu,
        lower = lower,
        upper = upper,
        na = na), class = "test_range")
}

#' @title Setup Test Values
#' @export
setup_test_values <- function(df_name, col_name, values, na) {
  structure(list(test_name = "test_values",
                 df_name = df_name,
                 col_name = col_name,
                 values = values,
                 na = na), class = "test_values")
}

#' @title Setup Test Unique
#' @export
setup_test_unique <- function(df_name, col_name, na) {
  structure(list(test_name = "test_unique",
                 df_name = df_name,
                 col_name = col_name,
                 na = na), class = "test_unique")
}

#' @title Setup Test Na
#' @export
setup_test_na <- function(df_name, col_name) {
  structure(list(test_name = "test_na",
                 df_name = df_name,
                 col_name = col_name), class = "test_na")
}

#' @title Apply test
#' @export
apply_test <- function(setup, df){
  UseMethod("apply_test")
  
}

apply_test.default <- function(setup, df, ...){
  
  warning(paste("apply_test does not know how to handle object of class ", 
                class(setup),
                "and can only be used on classes test_na, test_unique, test_values, and test_range"))
  
}

#' @title Tests for NAs
apply_test.test_na <- function(setup, df) {
  
  cls <- class_test_na(setup)
  test <- test_na(df, cls)
  test_result <- test_row(test)
  
  return(test_result)
}

#' @title Tests for uniqueness
apply_test.test_unique <- function(setup, df) {
  
  cls <- class_test_unique(setup)
  test <- test_unique(df, cls)
  test_result <- test_row(test)
  
  return(test_result)
}

#' @title Tests for Values
apply_test.test_values <- function(setup, df) {
  
  cls <- class_test_values(setup)
  test <- test_values(df, cls)
  test_result <- test_row(test)
  
  return(test_result)
}

#' @title Tests Range of Values
apply_test.test_range <- function(setup, df) {
  
  cls <- class_test_range(setup)
  test <- test_range(df, cls)
  test_result <- test_row(test)
  
  return(test_result)
}
